//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robotics.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int AuthorID { get; set; }
        public int PublisherID { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
